### ISSUE TITLE
Found a bug #1

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [tokland/feedback-test#42]
I'm having a problem with this

![]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1521629904562965623.png )

**Comment by tokland** [comment]
I'm having a problem with this

![]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1521629904562965623.png )
